server:
  servlet:
    context-path: /baicha
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/fantuandish?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: zhangxu1023
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        max-concurrency: 10  #消费者最大数量
#        prefetch: 1  #消费者每次从队列中取几个消息
#        default-requeue-rejected: true #消息消费失败后，重新进入消费队列中
#        retry:
#          initial-interval: 1000 #1秒后重试
#          enabled: true #启用发布重试
#          max-attempts: 4 #传递消息的最大尝试次数
#          max-interval: 10000 #尝试的最大时间间隔
#          multiplier: 1.0 #应用于先前传递重试时间间隔的乘数
  redis:
    database: 0
    host: localhost
    port: 6379
    password: zhangxu
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  thymeleaf:
    prefix: classpath:/templates/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
#logging:
#  config: log4j2.xml

